name: passive_liveness
description: "Ultra-lightweight passive face liveness detection using LiteRT (TensorFlow Lite) for Flutter on iOS and Android."
version: 0.0.5
homepage: https://github.com/andikatp/passive_liveness
repository: https://github.com/andikatp/passive_liveness
issue_tracker: https://github.com/andikatp/passive_liveness/issues

environment:
  sdk: ^3.12.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_litert: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/best_model.tflite
